### ISSUE TITLE
Beta "temp" mode not working

### ISSUE THREAD

**Issue by bilbolodz** [autopower/thermeq3#12]
I'm trying to use (beta) "temp" mode after enabling it (http://XXX/data/put/profile/temp, http://XXX/data/put/beta/yes), I'm receiving an error:

`Traceback (most recent call last):
  File "/root/thermeq3/nsm.py", line 45, in <module>
    if t3.intervals() == 0xFF:
  File "/root/thermeq3/thermeq3.py", line 593, in intervals
    self._do_beta()
  File "/root/thermeq3/thermeq3.py", line 702, in _do_beta
    self._do_profiles()
  File "/root/thermeq3/thermeq3.py", line 688, in _do_profiles
    sm, am, kk = profiles.do(self.setup.selected_mode, self.var.act_mode_idx, self.var.situation)
  File "/root/thermeq3/profiles.py", line 107, in do
    kv = temp_mode()
  File "/root/thermeq3/profiles.py", line 76, in temp_mode
    c_temp = int(table.sit["current_temp"])
TypeError: int() argument must be a string or a number, not 'NoneType'
`

**Comment by autopower** [comment]
Please check & test V224

**Comment by bilbolodz** [comment]
Where (and when) will it be available?

**Comment by autopower** [comment]
right now, in beta
https://github.com/autopower/thermeq3/tree/master/install/beta

**Comment by bilbolodz** [comment]
Hmmm... How to do upgrade in "gentle way"?
I can see in log:
---
2016/12/03 21:25:33 [INFO] Available file: thermeq3.zip, V224 with hash 8ed1b49f3468f83bb1f30d401df2c613
2016/12/03 21:25:33 [INFO] Actual version: 223, hash: 8ed1b49f3468f83bb1f30d401df2c613
2016/12/03 21:25:33 [DEBUG] Update is not necessary.
---
???

**Comment by autopower** [comment]
you can replace files in thermeq3 directory with V224
and then kill nsm.py process, or reset device

**Comment by bilbolodz** [comment]
OK, I know, it's "usual way" :-) I've asked how to use your "auto update procedure" but OK I will replace it manually.

**Comment by autopower** [comment]
just now I'm debugging autoupdate :)

**Comment by bilbolodz** [comment]
So please check also this (after upgrade to 224) I can see in log:
`2016/12/03 21:39:59 [DEBUG] Message queue: ['H', 'S']
2016/12/03 21:39:59 [DEBUG] ## process_msg ## bridge:
2016/12/03 21:39:59 [DEBUG] Message queue: ['H', 'S']
2016/12/03 21:39:59 [DEBUG] ## process_msg ## bridge:
2016/12/03 21:39:59 [DEBUG] Message queue: ['H', 'S']
2016/12/03 21:40:00 [DEBUG] ## process_msg ## bridge:
2016/12/03 21:40:00 [DEBUG] Message queue: ['H', 'S']
2016/12/03 21:40:00 [DEBUG] ## process_msg ## bridge:
2016/12/03 21:40:00 [DEBUG] Message queue: ['H', 'S']
2016/12/03 21:40:00 [DEBUG] ## process_msg ## bridge:
2016/12/03 21:40:00 [DEBUG] Message queue: ['H', 'S']
2016/12/03 21:40:00 [DEBUG] ## process_msg ## bridge:
`

**Comment by autopower** [comment]
target yun?

**Comment by bilbolodz** [comment]
Generally yes, in details: Iduino Yun Shield (http://www.geeetech.com/wiki/index.php/Iduino_Yun_Shield).

**Comment by autopower** [comment]
V225 onsite :)

**Comment by bilbolodz** [comment]
No yet?

**Comment by autopower** [comment]
Please reopen if you have problems.

**Comment by bilbolodz** [comment]
Not working, after putting http://XXX/data/put/profile/temp script quits with an error:
`Traceback (most recent call last):
  File "/root/thermeq3/nsm.py", line 59, in <module>
    if t3.intervals() == 0xFF:
  File "/root/thermeq3/thermeq3.py", line 617, in intervals
    self._do_beta()
  File "/root/thermeq3/thermeq3.py", line 726, in _do_beta
    self._do_profiles()
  File "/root/thermeq3/thermeq3.py", line 712, in _do_profiles
    sm, am, kk = profiles.do(self.setup.selected_mode, self.var.act_mode_idx, self.var.situation)
  File "/root/thermeq3/profiles.py", line 128, in do
    kv = temp_mode()
  File "/root/thermeq3/profiles.py", line 97, in temp_mode
    kv = table.temp[k]
TypeError: list indices must be integers, not list`

Yahoo WOEID seems to be correct because in log I can see:
`2016/12/04 22:46:42 [INFO] Difference between Yahoo and OWM temperatures. Yahoo=-1.0 OWM=3.0
2016/12/04 22:46:42 [INFO] Current temperature in Lodz is -1, humidity 90%
2016/12/04 22:46:42 [DEBUG] OWW interval updated to [420, 1260, 1260]`

which is correct name for my localisation

**Comment by autopower** [comment]
V226 is onsite

**Comment by bilbolodz** [comment]
Now it's working:
`2016/12/05 10:08:51 [INFO] Switching temp mode to -10 ~ 0`

autoupdate feature is working as well. Thanks.
