### ISSUE TITLE
Nice/status web page

### ISSUE THREAD

**Issue by bilbolodz** [autopower/thermeq3#18]
It could be a good idea (in my opinion) to add to web page (nice.html status.xml) information about heating/not heating state. It allow to collect and (plot) information about "whole heating system" by external program (e.x. mrtg).

**Comment by bilbolodz** [comment]
It could be also a good idea to signal (at web page) that ECO mode (e.x. using ECO button) is on
It could be also a good idea to implement signaling ECO mode ON at arduino board (using additional LED). . I've switched ECO mode accidentally a few times and I was wondering why it's so cold in the house :-)

**Comment by autopower** [comment]
Please take a look at [simple dashboard](https://github.com/autopower/thermeq3/tree/master/install/dashboard)

**Comment by bilbolodz** [comment]
I've tried. Generally it's working BUT dashboard claims that "Weather in Bratislava ....." but my location is other ("yahoo_location": "505120" "owm_location": "3104132"). I've looked into code and looks thats dashboard is trying to read http://localhost:8180/location.json and in case of failure silently assume Bratislava as default (

`try:
    location = d["location"]
except:
    location = "823123"
`
In my setup there are NO file location.json and that's the problem.

I also noticed that config_me.py ignores my Yahoo location ID  and puts Bratislawa ID into config file.
I've edited config file "by hand" and now nsm.py knows my correct location.

**Comment by bilbolodz** [comment]
Where location.json should be created by install script? Today I've tried "upgrade" script and file still doesn't exists.

**Comment by bilbolodz** [comment]
Found location.json in root folder. Unfortunately it contains :"yahoo_location" json variable but dashboard.py expects "location".

**Comment by autopower** [comment]
fixed

**Comment by bilbolodz** [comment]
Working fine.
