### ISSUE TITLE
Autoupdate NOT working

### ISSUE THREAD

**Issue by bilbolodz** [autopower/thermeq3#22]
2017/10/10 20:04:29 [DEBUG] Doing autoupdate...
2017/10/10 20:04:30 [INFO] Available file: thermeq3.zip, V252 with hash 24c892aa8e8b9f5533e56324888f1956
2017/10/10 20:04:30 [INFO] Actual version: 254, hash: bb85a964dd3827dd665d0c4a84e5f522
2017/10/10 20:04:30 [DEBUG] Update is not necessary.
2017/10/10 20:04:30 [DEBUG] Updating variables...

**Comment by autopower** [comment]
Actual version (254) > Available version (252) = no update

**Comment by bilbolodz** [comment]
I see so I need to update manually?

**Comment by autopower** [comment]
yes, manually. I'll testing 255, but this version needs more tests.
