### ISSUE TITLE
Malformed "ignored" message

### ISSUE THREAD

**Issue by bilbolodz** [autopower/thermeq3#28]
In version 257 (not checked in later versions) part of bridge.json seems to be malformed (problem with json parsing in javascript): 

`"{u'': 1924991999, '140CBF': 1508279082.8247181, '140D03': 1508279082.8245169, '13EDAA': 1508279082.8246146}"`

Message from parser: SyntaxError: Unexpected token u

**Comment by autopower** [comment]
Fixed in 268
