### ISSUE TITLE
Another Dashboard Enhancement

### ISSUE THREAD

**Issue by pepelillo** [autopower/thermeq3#31]
Love this project. It is almost 100% what I was looking for, unfortunately I'm not a Python dev, but I was able to install and make it work.
But I'd like to guess some Dashboard enhancement, I've seen this project; https://github.com/stephenmhall/PiHeating and love it's dashboard https://forum.mysensors.org/topic/2485/boiler-control-from-max-cube-to-drayton-boiler-via-raspberry-pi-vera-mysensors.

Also think that a specific "button" in the dashboard for set boiler on/off manually if necessary would be convinient.

Thanks for this great project.

**Comment by autopower** [comment]
Check old (0.15+) dashboard, or completely new dash in alpha channel.
