### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by asantaga** [autopower/thermeq3#6]
Hi 

Excellent repository/project, Ive just purchased a Max trv,cube and one wall stat to see how they worked. The only negative I could see was the fact that the cube cant control the boiler, your script solves this!

One question, I noticed you are using the arduino Yun,, why not just a RaspberryPI? or even a C.H.I.P. device? (getchip).. Nothing against the yun but im perplexed to why you needed Python and a arduino sketch whereas python could do it all..

Just curious

Angelo
ps hope logging an issue is the right way to communicate this

**Comment by autopower** [comment]
Hello,
no rocket science, yun was just a "shelf away", and python is part of default installation, thus thermeq3 is written in python. 

m

PS: just like FB page and send message if you are curious
