### ISSUE TITLE
 disable the duty circle.

### ISSUE THREAD

**Issue by chrisj8727** [autopower/thermeq3#8]
it is possible to disable the duty circle.
This is annoying especially during testing.
thanks in advance chris

**Comment by autopower** [comment]
What you mean by duty circle?

**Comment by chrisj8727** [comment]
The duty cycle describes a statutory limit of the airtime of devices in the
868 MHz range. The objective of this scheme is to the function of all in
the 868 MHz range to ensure working devices. In the frequency range used by
us, the maximum transmission time of each unit 868 MHz is 1% of one hour
(so 36 seconds in an hour). The devices may be used in achieving the
1%-limit no longer send, until the time limit is over.


chris

2016-09-21 6:42 GMT+02:00 Michal Cheben <notifications@github.com>:

**Comment by autopower** [comment]
Thermeq3 does not manipulate communication between device and cube in any way, so informatiom stored "in cube" is based on normal transmission between device and cube.
